### ISSUE TITLE
свяжитесь, пожалуйста

### ISSUE THREAD

**Issue by innovup** [SerHappy/CarWebBot#2]
Здравствуйте.
Свяжитесь пожалуйста через fl по этому проекту, т.к. есть желание развивать проект. Надеюсь, есть возможность. Жду

**Comment by SerHappy** [comment]
Добрый день!
К сожалению, не смогу продолжить работу над проектом. К FL доступа нет, не смог вам там ответить.

**Comment by innovup** [comment]
понятно, жаль. Спасибо за ответ
